会場を株式会社インプレスに更新した
hikky8man/ichiyasaGitSample pull request #1
Opened 2024-11-02 07:37 UTC by hikky8man

###
会場を変更

2024-11-02 07:41 UTC, hikky8man commented
修正を確認

2024-11-03 05:06 UTC, yukinonnon requested changes
指摘内容の確認をお願いします。

2024-11-03 05:06 UTC, yukinonnon commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社インプレスを「」で囲ってください

2024-11-03 05:14 UTC, hikky8man commented
修正したものをpushしたのでご確認ください。

2024-11-03 05:16 UTC, yukinonnon approved these changes

2024-11-03 05:23 UTC, merged